version: '3'

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php
    labels:
      - "traefik.frontend.rule=Host:${TRAEFIK_HOSTNAME}"
      - "traefik.port=80"
    networks:
      - web

  php:
#    image: jorge07/alpine-php:7.1-dev-sf
    build: ./etc/dev/php
    ports:
      - "2323:22"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - .:/app:rw
    depends_on:
      - mysql
      - rmq
    networks:
      - web
  workers:
    image: jorge07/alpine-php:7.1-dev-sf
    volumes:
      - .:/app
    command: ['/app/bin/console', 'rabbitmq:multiple-consumer', 'events']
    networks:
      - web

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web

  rmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      - "traefik.frontend.rule=Host:rmq.phishd.test"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - web

  kibana:
    image: kibana:5.6
    ports:
      - 5601:5601
    volumes:
      - "./etc/dev/kibana/config:/usr/share/kibana/config"
    labels:
        - "traefik.frontend.rule=Host:kibana.phishd.test"
    networks:
      - web

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
    networks:
      - web

volumes:
  db_data:

networks:
    web:
        external: true
