App\Domain\User\Query\UserView:
  type: entity
  table: users
  id:
    uuid:
      type: uuid_binary
  embedded:
    credentials:
      class: App\Domain\User\ValueObject\Auth\Credentials
    name:
      class: App\Domain\User\ValueObject\Name
      columnPrefix: false